[build]
  publish = "/"
[[headers]]
  for = "/.well-known/apple-app-site-association"
  [headers.values]
    Content-Type = "application/json"
    X-Apple-App-Site-Association = "domain"
    Access-Control-Allow-Origin = "*"
